### ISSUE TITLE
Update Terminology

### ISSUE THREAD

**Issue by dvachez** [i-adopt/terminologies#1]
Updating a new version, with new metadata and new files (ttl, json)
Title: Biodiversity Thesaurus
URL: https://skosmos.loterre.fr/BLH/en/
Types: SKOS Vocabulary; Thesaurus
Domains: biodiversity conservation; ecology; environmental sciences
Keywords: biodiversity; ecology
Languages: EN; FR
Concepts covered: Variable; Property; Entity
Alignments to: ENVTHES; AGROVOC; GEMET; ENVO

**Comment by SirkoS** [comment]
I added your update. Can you please check it (make sure to refresh your cache)?
If everything is ok, we can close here.

**Comment by dvachez** [comment]
Thanks a lot. I have checked the update and everything is Ok, except for json file : alignments with AnaEE, GACS and EARTh have not yet been realized

**Comment by SirkoS** [comment]
Thanks for checking!
I removed those alignments for now.
