### ISSUE TITLE
Are open questions in the final section on Issues and Challenges okay?

### ISSUE THREAD

**Issue by gwemon** [i-adopt/terminologies#10]
Feedback from @mabablue transferred from team discussion:
About the last sections with the issues and challenges I think it is really hard to have more closed questions. I think I could immediately add some issues but I couldn't group them or generalize them for more closed questions. I think if you are already asking for all these details before, you could also add this last part.

**Comment by SirkoS** [comment]
I'm not completely sure I understand what you're getting at, but I think having those open question might give us some pointer for things to focus in the analysis. Basically checking that the issues that one project mentions are solved with any of the others.

**Comment by graybeal** [comment]
Why wouldn't open questions be OK? I agree with @SirkoS here.
