### ISSUE TITLE
Convergence with SSN survey attributes

### ISSUE THREAD

**Issue by gwemon** [i-adopt/terminologies#11]
@gwemon Suggested that we might want to converge with some of the attributes used in the SSN survey https://www.w3.org/2005/Incubator/ssn/wiki/SSN_Suggested_Key_Ontology_Intro_Attributes

**Comment by gwemon** [comment]
@mabablue's response:
Regarding the SSN survey questions, I would find relevant:

- Status: Is this an actively maintained ontology, or not? Would you consider it 'complete', or not?

- Reference Documentation: Does the ontology contain references to relevant publications or specification documents? (instead of the question about Additional semantic model information)

- Range of subject matter: With respect to sensors, is this ontology narrowly focused, moderately broad, or comprehensive? we could reuse this accordingly: With respect to observable property descriptions, is this ontology narrowly focused, moderately broad, or comprehensive?

**Comment by SirkoS** [comment]
Some of the mentioned attributes are already included in our survey (e.g., "primary purpose" == "main usecase", "adoption" == "repos/systems/.. using the terminology"). As for the suggested additions, I agree with status and reference description.

"Range of subject matter" is less informative, I guess, compared to the schematics we are asking for. On the other hand, it might be easier to provide this ...

**Comment by graybeal** [comment]
Why do you want this information?  If it's for general description of that ontology or model, I wouldn't bother asking for the user to provide it—we can gather that information yourself fairly easily if it isn't already known to us. 

In fact, even if you are looking for a basis for understanding whether a particular model might be a good choice, I'd not ask the user to provide this information. Their input will be anecdotal and not comparable to other answers.  

In general, for comparing the usefulness of models, I'd wish for something more precise and measurable. (MOD for ontologies is a start, and I've done a set of criteria for vocabularies that would be informative.)  Also, please note the list of useful metrics/metadata for ontologies is different than for models, and I think (as previously discussed?) we'll be working more with models into which ontology concepts can be inserted. (There are few or no full ontological models for what we're trying to do, to my knowledge.)

**Comment by mabablue** [comment]
@graybeal. I agree with your suggestion about MOD (to be used after the collection, and by us to evaluate their fitness)  and would now skip range of subject matter, but still keep status and reference documentation. Where I struggle a bit, and am not sure if we all talk about the same is this part: <ctrl+1> we'll be working more with models into which ontology concepts can be inserted. (There are few or no full ontological models for what we're trying to do, to my knowledge.) <ctrl+1> . I think we have to deal with more than one type of semantic resource (terminology) - with conceptual models (including ontologies) and with thesauri/controlled lists with the terms we use to annotate datasets. (see discussion on https://github.com/i-adopt/glossary/issues/7)

**Comment by gwemon** [comment]
MOD?

**Comment by mabablue** [comment]
@gwemon it is the metadata vocabulary for ontology (Clement Jonquet) see here https://drive.google.com/drive/folders/1qM9MflNUv4k5mZmdJd_QAF7CB_biEvqK
