### ISSUE TITLE
Questionnaire - List of Issues

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [i-adopt/terminologies#13]
- I suggest we use consistent terms, resource vs terminology

- What was the main use case for the development of this resource? -->i am not sure if everyone understands what is 'use case'. so it would great if we can provide some examples (short)

- Please describe the type of data supported by the terminology  --> 'type of data' is unclear. for example, common formats of RDF are N-Triples, Turtle, JSON-LD and RDF/XML. So is the 'type of data' refers to RDF or serialization format?

- dimensions (eg spatio-temporal variables) - what are 'spatio-temporal variables'?

- I suggest reordering the following questions on nitrogen case study 1.To what chemical database(s) .....2. What kinds of nitrogen-related variables a.. 3.Please provide a list of nitrogen-related variable...

**Comment by mabablue** [comment]
should we call it user-story instead and this is defined in our github?

**Comment by mabablue** [comment]
I think your list here is not so appropriate each of the issues are good to have them listed separately as single issues.

**Comment by mabablue** [comment]
Please describe the type of data supported by the terminology --> 'type of data' - I think here we don't refer to terminologies but to the datasets themselves... e.g. observation data about nitrogen deposition in ecosystem (this is not asking for the format at all). But I could be wrong, @gwemon?

**Comment by mabablue** [comment]
I suggest we use consistent terms, resource vs terminology - you are right and we need to fix the terms we use in the glossary issues see here: https://github.com/i-adopt/glossary/issues

**Comment by kitchenprinzessin3880** [comment]
the questions above have been assigned as individual issues.
