### ISSUE TITLE
closing statement suggestion

### ISSUE THREAD

**Issue by graybeal** [i-adopt/terminologies#15]
This is on the last page of the RRING survey I just took. We should have something comparable on our closing survey, and a link to the project page.

> Thanks again for taking the time to complete this survey in full!
> Our next steps will include careful analysis of your responses, along with others from around the world.
> At a later date, anonymous results from this survey will be made fully, publicly and freely available on the RRING project website: rring.eu.
>

**Comment by mabablue** [comment]
I agree

**Comment by pbuttigieg** [comment]
Agreed, should we also post results via the WG mailing list and webpage?

**Comment by mariutzica** [comment]
I completely agree.
