### ISSUE TITLE
Consistent Term

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [i-adopt/terminologies#16]
I suggest we use consistent terms, resource vs terminology

**Comment by kitchenprinzessin3880** [comment]
@mabablue : I suggest we use consistent terms, resource vs terminology - you are right and we need to fix the terms we use in the glossary issues see here: https://github.com/i-adopt/glossary/issues

**Comment by gwemon** [comment]
Done.

**Comment by gwemon** [comment]
Also I have added a footnote to the introduction with the definition we had in the case statement for "terminology".

**Comment by kitchenprinzessin3880** [comment]
@gwemon perfect!
