### ISSUE TITLE
Main Use Case

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [i-adopt/terminologies#17]
What was the main use case for the development of this resource? -->i am not sure if everyone understands what is 'use case'. so it would great if we can provide some examples (short)

**Comment by kitchenprinzessin3880** [comment]
@mabablue : should we call it user-story instead and this is defined in our github?

**Comment by gwemon** [comment]
user stories and use cases are different in my opinion and I think that use case is what is needed here. However if we have to change it then I'd prefer to go for what SSN used for their ontology attributes which was: "Primary purpose/target" to ask why the ontology was created. Can we have a show of hands (thumb up / thumb down) in support or in rejection of replacing "use case" by "primary purpose or target".

**Comment by gwemon** [comment]
Will replace "main use case" with "primary purpose" in consolidated version of the Q for OPT providers

**Comment by gwemon** [comment]
Done.
