### ISSUE TITLE
Type of data

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [i-adopt/terminologies#18]
Please describe the type of data supported by the terminology --> 'type of data' is unclear. for example, common formats of RDF are N-Triples, Turtle, JSON-LD and RDF/XML. So is the 'type of data' refers to RDF or serialization format?

**Comment by kitchenprinzessin3880** [comment]
@mabablue : I think here we don't refer to terminologies but to the datasets themselves... e.g. observation data about nitrogen deposition in ecosystem (this is not asking for the format at all). But I could be wrong, @gwemon?

**Comment by gwemon** [comment]
@mabablue yes that's correct. @kitchenprinzessin3880 The descriptive text below the title of this question says: "This helps us understand what may affect your naming approach. Any kind of information related to the "type of data" supported can be helpful here including specific resource formats, content domain, or something else."

**Comment by kitchenprinzessin3880** [comment]
@gwemon @mabablue in that case, can you please include examples (like the one barbara stated before) next to the question?
"This helps us understand what may affect your naming approach. Any kind of information related to the "type of data" supported can be helpful here including specific resource formats, content domain, or something else. **For example...**
