### ISSUE TITLE
Are we asking for too many details?

### ISSUE THREAD

**Issue by gwemon** [i-adopt/terminologies#2]
Feedback on questionnaire from @mabablue transferred from team discussion:
you try to collect already many details, I hope people will take the time to answer them all within this form. It will take them at least half a day to fill this out, what is your estimation? to whom are we going to distribute this questionnaire? To the whole group, to terminology providers we know?

**Comment by gwemon** [comment]
@mabablue it should not take more than half hour to fill in I would think. Half a day? which sections of the questionnaire do you find difficult/time consuming to answer?

**Comment by graybeal** [comment]
I'm leaning toward >2 hours. It took me 30 minutes just to think about each question the first time (not counting 30 minutes to make suggestions) and I'm pretty expert in what you're talking about. 

If you're asking people to put in more than 15 minutes, it is a big ask, even if they are all committed to figuring out this problem. So every question needs to be Really Useful for almost all of the answers.

Also keep in mind this questionnaire is advertising, not just data collection. See next paragraph.

@mabablue I think the target audience should be "People who have wrestled with naming conventions and want to contribute to a robust workable solution."  So it's down-selected to people who are pretty engaged already, and who will have important perspectives (and may wish to participate in this group). If the questionnaire is clear and they can recognize the value of the questions, it will attract people who have thought about it.
