### ISSUE TITLE
Reorder questions on nitrogen case study

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [i-adopt/terminologies#20]
I suggest reordering the following questions on nitrogen case study 1.To what chemical database(s) .....2. What kinds of nitrogen-related variables a.. 3.Please provide a list of nitrogen-related variable...

**Comment by gwemon** [comment]
@kitchenprinzessin3880 I have just tried it but I am not convinced it works because the respondent might wonder what we mean by "chemical database". Why did you feel this was important?

**Comment by kitchenprinzessin3880** [comment]
@gwemon i thought you may want to start from database and then followed by how the terms in database used in representing the nitrogen variables..

**Comment by gwemon** [comment]
@kitchenprinzessin3880 Some terminologies might not use a reference source for chemical names. You can have a terminology with chemical substance names that has no links to e.g. CHEBI or CAS. Also not all chemical substances or compounds are represented these registries (some might not have any registry as yet). So the registry is very much an added value to the terminology.
