### ISSUE TITLE
Merge section 3 and 4 of the questionnaire

### ISSUE THREAD

**Issue by mabablue** [i-adopt/terminologies#21]
I propose to merge the questions from 3 and 4. These are the reasons:
First:
- In section 3 you find the question about the model used

- In section 4 you ask to provide a diagram about the relationships, both are not Nitrogen related 
or you put the question about the model used in 4 or you have just one section

Second: 

- I propose to use the spreadsheet template (in section 4) to fill in also the examples for the nitrogen use case and skip the question in section 3 (please provide a list of nitrogen-related observable property names). The spreadsheet should be slightly changed to be able to add more than one example... see this https://github.com/i-adopt/terminologies/raw/master/Template%20for%20OPT%20providers.xlsx
I added also the contact name to be able to merge tables at the end without loosing the provenance info.

So in this merged section you would have in total 6 questions:

1) What kinds of nitrogen-related observable properties are already described...
2) To what chemical databases do you refer...
3) What semantic model do you use for describing the observations
4) Please proived a diagram of the relationships linking the concepts used in your terminology
5) Please provide a list of terms and definitions of concepts with examples for the N-related observable properties
6) Additional semantic model information

**Comment by mariutzica** [comment]
@mabablue I agree that it makes sense to merge the information you describe. 

I think it would be helpful if the ordering of the questions went from more generic/domain-independent to more specific/domain dependent. Or we could reverse the order if that seems more logical. Here are my thoughts for the ordering of the questions:

Part 1. Questions related to the top-level ontology.

Do you use a top-level ontology? If so, please provide a list of top-level/domain-independent categories that you use to describe observable properties. (This will likely be some kind of simple taxonomy that includes ideas such as property, phenomenon, etc.; they may either pick an existing top-level ontology such as BFO, or they may have created their own, or they may not use one at all).

Part 2. Questions related to the relationships that combine top-level concepts.

Provide the semantic/conceptual model used for describing observations. This is the model the combines the top level concepts to form more complex ideas. (Again, this may be an established model as in Q3, a custom created model, or they may not use a model at all. This is the part where they could also provide a diagram, if available -- Q4 above. In some cases, parts 1 and 2 may be represented by the same resource.)

Part 3. Questions related to nitrogen.

Provide a list of observable properties represented related to nitrogen.  This is the section where questions 1, 2 and 5 would go.

**Comment by mabablue** [comment]
@mariutzica ok I see what you mean. I think it would make sense to reorder these. I have made the changes see here https://docs.google.com/forms/d/1bUKcMviJr9UGUS6haVo_IcR0TRVxdNAISsPouE55Fpo/edit...
I did not add the question mentioned in part 1, because everything would also be understandable in the excel sheet for question 5 I think

**Comment by mariutzica** [comment]
@mabablue yes, I think that looks great.

**Comment by gwemon** [comment]
@mabablue @mariutzica I think this merged section needs work because it now seems to ask questions that are related to "your data"/"the data you are responsible for" as opposed to "your terminology". It's quite confusing.

**Comment by mariutzica** [comment]
@gwemon Yes, I see what you mean. How about the following rephrasing:

Q1: What semantic or conceptual model(s) do you use for describing observable properties?
Q2: Please provide a diagram or any other schematic representation of the relationships linking the concepts you use when describing observable properties.
Q3: What kinds of nitrogen-related observable properties are of relevance for the data you are responsible for? (keep this the same as it seems appropriate here)

**Comment by gwemon** [comment]
Also I am not convinced about the need to merge. Section 3 as I had it in the original questionnaire was specifically about nitrogen-related variables with no mention/question about any conceptual semantic model or conceptual model. This was on purpose because I thought we also needed to gather information about terminologies that may not have a semantic/conceptual model element in their design. In your proposed merged design, this is now so prominent that it might put people off from giving information about their terminologies. I can't really see the gain.

**Comment by gwemon** [comment]
@mabablue @mariutzica actually I have just realised that this ticket is now linked to the "consumer" questionnaire although the merging was also done in the "provider" one. I am confused.
