### ISSUE TITLE
Add a role question?

### ISSUE THREAD

**Issue by mabablue** [i-adopt/terminologies#22]
I propose to add this question:
What is your role in relation to the terminology you want to describe

- developer
- curator
- provider
- other: ___

**Comment by gwemon** [comment]
This needs to allow multiple selections.

**Comment by graybeal** [comment]
other categories to include: contributor; user; manager; funder

**Comment by gwemon** [comment]
I have added the roles:
developer
curator
provider
contributor
Others: --
I have not added the other roles in order to keep it light. The "other" option gives the option to add more.
