### ISSUE TITLE
Add a question about the domain?

### ISSUE THREAD

**Issue by mabablue** [i-adopt/terminologies#23]
I propose to add a question about the domain the terminology is representing. 
I think it is helpful to know if this is a specific subdomain (and which) or more a general terminology for environmental research

**Comment by gwemon** [comment]
The list of domains need to be the same as the one used for the "Consumer" questionnaire. We need to agree on what domains the list should have. Maria suggested using the UNESCO list (http://skos.um.es/unesco6/00/html) at our last meeting (or at least a subset of it). Alternatively we could use 14 top level GCMD science keyword categories (see https://gcmd.nasa.gov/KeywordSearch/Keywords.do?Portal=GCMD&KeywordPath=Parameters%7CHome&MetadataType=0&Columns=0#maincontent)
