### ISSUE TITLE
Semantic model used

### ISSUE THREAD

**Issue by mabablue** [i-adopt/terminologies#24]
- Is conceptual model a better term?
- do we need explaining names for the models listed like EFO or are acronyms ok?
- I would add Complex Property Model, OBOE, Scientific Variable Ontology, SOSA/SSN
- I would delete QUDT, SWEET

**Comment by mariutzica** [comment]
Here are my thoughts:

- Is conceptual model a better term?
I think depending on the situation, one or the other term may be more appropriate. Perhaps it would be best to use both?

- do we need explaining names for the models listed like EFO or are acronyms ok?
I would vote for spelling out the name.

**Comment by gwemon** [comment]
I agree about spelling the acronyms and I'd suggest to use "What semantic or conceptual models do you use...".
The list I originally provided for this section was extracted from our case statement. Why are SWEET and QUDT no longer suitable?

**Comment by mabablue** [comment]
@gwemon because I think we need them in the question about units instead.. they are not suited to address the whole description of observable properties I think (at lease QUDT does not)

**Comment by graybeal** [comment]
Re SWEET, QUDT: Some people almost certainly use them for naming their nitrogen data (because some include units within the name). If you want to use them elsewhere feel free, don't take them away from this global question.

**Comment by gwemon** [comment]
I think this issue has been addressed and can be closed. We can re-open if required.

**Comment by mabablue** [comment]
@gwemon I think we should align the approaches here: 
question .... what semantic or conceptual model(s)  if any do you use to describe the observations?
