### ISSUE TITLE
Use of acronym OPT in questionnaire for consumers

### ISSUE THREAD

**Issue by mabablue** [i-adopt/terminologies#25]
I am not sure if it is ok to use only the acronym OPT (Observable Property Terminology) in the questions after having explained it in the introductory text. It would make the questions shorter... and why mention the acronym if later not used... see the new questionnaire here: https://docs.google.com/forms/d/1X5xE492Tir5yPi0BrmF2aA4bOcozYafzE_0olrL7K64/edit

**Comment by kitchenprinzessin3880** [comment]
what is knowledge acquisition in the context of this question?

**Comment by kitchenprinzessin3880** [comment]
suggest adding 'data search' as part of the choices provided.

**Comment by kitchenprinzessin3880** [comment]
URL of the main (meta)data repository for which you use OPT
- may i know the purpose of this question?

**Comment by mabablue** [comment]
knowledge acquisition - here I meant a researcher might want to know more e.g. about the methods used to observe a property (looks up the terminologies for that)

**Comment by mabablue** [comment]
The purpose is e.g. data annotation of the datasets with the terminologies
