### ISSUE TITLE
naming of nominal properties

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [i-adopt/terminologies#29]
Do you need also the naming of nominal properties? 
I am not sure if the i understand the question fully. are you asking the data provider if they use the terminology to annotate nominal properties?

**Comment by mariutzica** [comment]
Yes, that is the intention for this question. I like @kitchenprinzessin3880 's rewording: "Is this terminology used to annotate nominal properties?"

**Comment by mabablue** [comment]
@mariutzica the issue is that we ask consumers. so they could use more than one terminology. I want to ask them if they need for their work terms for nominal properties. If they use it to annotate is another question this refers more to the question: for which pupose do you use OPT?

**Comment by mariutzica** [comment]
@mabablue oh I misunderstood, thanks for clarifying. How about: "Do you need the capability to annotate nominal properties?"

**Comment by gwemon** [comment]
@mariutzica yes this work for the "consumer" questionnaire. For the provider questionnaire I would suggest using: "Does your terminology support or include nominal properties"

**Comment by graybeal** [comment]
what's a nominal property?

**Comment by gwemon** [comment]
@graybeal non-quantifiable properties. 
This is BIPM's definition: https://jcgm.bipm.org/vim/en/1.30.html
I wanted to include them explicitly so that they are not forgotten in our discussions about the kind of observations and measurements we need to cover.

**Comment by graybeal** [comment]
Thanks! If you want to call them 'nominal' please include the definition. i'm pretty sure I've never heard that term for them.

**Comment by gwemon** [comment]
@graybeal the definition is already included in the questionnaire but if "nominal property" does not mean much to many people then it would be best to choose another term. Any suggestions?

**Comment by gwemon** [comment]
In the OPT provider questionnaire changed to "Does your terminology include terms for qualitative observations?"

**Comment by kitchenprinzessin3880** [comment]
@gwemon sorry to reopen this again. i have minor remark:
(aka nominal properties? * - closing bracket is missing..

**Comment by gwemon** [comment]
Fixed.
