### ISSUE TITLE
Do we need a separate country box?

### ISSUE THREAD

**Issue by gwemon** [i-adopt/terminologies#3]
Comment from @mabablue Affiliation including country... I must say I oversaw country at the first moment. Also If you think it is relevant for quering later, the country question should be a separate one.

**Comment by gwemon** [comment]
Initially I had the country in a separate box but I decided to merge it to the affiliation after John @graybeal questionned if we needed to ask this at all? Do we? For me this is just additional info about the respondent, his/her affiliation and asking for the country helps in cases when the affiliation is not sufficient to localise it. It is not essential info.

**Comment by mabablue** [comment]
Then just leave it as it is.

**Comment by graybeal** [comment]
Or just leave it out and go back and ask them if you can't figure it out. Asking n > 20 people to provide an answer that you won't need for n-1 surveys is problematic.

**Comment by pbuttigieg** [comment]
We should have a separate box I think.

 Regionalisation is a key thing to have : capacities are very region/nation specific at times.

**Comment by gwemon** [comment]
I agree with pbuttigieg here. Also shall we ask a question about the language supported by the terminology? So far we have assumed that such resource only exists in the english language.
