### ISSUE TITLE
Add question about language supported by terminology

### ISSUE THREAD

**Issue by gwemon** [i-adopt/terminologies#30]

**Comment by gwemon** [comment]
So far we have assumed that we're only interested in terminologies in the english language however it would be very valuable to open up to other languages. I will add a question on this (once we've consolidated which version to take forward).

**Comment by mabablue** [comment]
add related question for consumers/providers

**Comment by mabablue** [comment]
users: are you using any non-English terminology? if so which language
providers: are you managing any non-English terminology? and if so which language

**Comment by gwemon** [comment]
@mabablue Are we leaving this out? If we have room for it then I would suggest adding "for observable properties" e.g.
Consumers: Are you using a non-english terminology for observable properties? if so which language
Providers:: Are you managing non-english or multilingual terminologies for observable properties? if so which language(s) do you support?

**Comment by mabablue** [comment]
Hi Gwen,
you con see the changes I did again.
Language is now in the general part included

barbara

Von: Gwen Moncoiffé <notifications@github.com>
Gesendet: Dienstag, 21. Jänner 2020 22:39
An: i-adopt/terminologies <terminologies@noreply.github.com>
Cc: Magagna Barbara <Barbara.Magagna@umweltbundesamt.at>; Mention <mention@noreply.github.com>
Betreff: Re: [i-adopt/terminologies] Add question about language supported by terminology (#30)


@mabablue<https://github.com/mabablue> Are we leaving this out? If we have room for it then I would suggest adding "for observable properties" e.g.
Consumers: Are you using a non-english terminology for observable properties? if so which language
Providers:: Are you managing non-english or multilingual terminologies for observable properties? if so which language(s) do you support?
