### ISSUE TITLE
Survey comments

### ISSUE THREAD

**Issue by alko-k** [i-adopt/terminologies#42]
The survey looks very good, so well done for your efforts.
My comments:
#Number the questions so people can refer back to them
#Same question repeated
Please name the main data repository, system or data product that uses the terminology for observable properties.  
Please name the main data repository, system or data product for which you use a terminology for observable properties. 

#Same answer different question
Please name the main terminology you use for describing observable properties
Which is the observable property terminology you want to describe?

#Allow multiple selections for the following question
What semantic or conceptual model(s) if any do you use to describe your data?

I like the print your answers ;-)
Hope it helps
Alexandra

**Comment by mabablue** [comment]
Hi Alex,
#Same question repeated
Please name the main data repository, system or data product that uses the terminology for observable properties.
#Same answer different question
Please name the main terminology you use for describing observable properties
Which is the observable property terminology you want to describe?
this is only true if you are both a provider and a consumer. But the perspective and the context is another one.

**Comment by mabablue** [comment]
I will implement your other two suggestions! thanks

**Comment by alko-k** [comment]
> Hi Alex,
> #Same question repeated
> Please name the main data repository, system or data product that uses the terminology for observable properties.
> #Same answer different question
> Please name the main terminology you use for describing observable properties
> Which is the observable property terminology you want to describe?
> this is only true if you are both a provider and a consumer. But the perspective and the context is another one.

Thanks @mabablue , a suggestion then would be to include  "from the provider's perspective" and "from the consumer's perspective" to each question. 

Alexandra

**Comment by mabablue** [comment]
I tried to consider your consideration in the block of the questions
