### ISSUE TITLE
For which purpose do you use observable property terminologies?

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [i-adopt/terminologies#43]
For which purpose do you use observable property terminologies?
data values annotation - ok
metadata record annotation - remove record
linked data 
data search interface
harmonizing metadata - what is metadata harmonization?
data (products) integration

**Comment by mabablue** [comment]
no I think it is important to have record there, it is saying that you annotate the instance level of metadata

**Comment by mabablue** [comment]
metadata harmonization is done for the same purpose then metadata record annotation, to avoid individual text, so I think I can delete metadata harmonization, thanks!

**Comment by kitchenprinzessin3880** [comment]
ok thanks.
