### ISSUE TITLE
Which unit ontology do you use?

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [i-adopt/terminologies#45]
1. Which unit ontology do you use?
replace ontology with terminology

2. ODM2 has several collections, suggest to specific specific collection, such as ODM2 Unit (http://vocabulary.odm2.org/units/)

**Comment by mabablue** [comment]
this is hard to implement, it becomes clear with the examples in the excel file

**Comment by kitchenprinzessin3880** [comment]
ok should be fine if you include examples in the excel file. to be consistent with other questions, please 'ontology' with 'terminology' in the question.
