### ISSUE TITLE
Make it clear that section on semantic model only relevant for those who use a semantic model

### ISSUE THREAD

**Issue by gwemon** [i-adopt/terminologies#7]
Feedback from @mabablue  transferred from team discussion:
What semantic model(s) do you use for describing the observations? This might be relevant only for some terminologies. If you describe a controlled list, there might be no model it is based on. You would ask this when you are interested to know something about annotation practices. But we could also rephrase this a bit, like: Is your terminology based on a semantic model?

**Comment by gwemon** [comment]
Agree - I thought I had already specified this but must have been lost in my few iterations of the form. I'll fix this.

**Comment by pbuttigieg** [comment]
We should give some clarification / examples of what "semantic model " means in a blurb on the question

**Comment by gwemon** [comment]
see #24 - we decided to broaden this question to ask about any conceptual model used to describe the observations. This include both fine grain conceptual models and high level ones. I believe this issue can now be closed. If concerns persist we can discuss them in a new ticket.
