### ISSUE TITLE
Ensure question about concept descriptions is understandable by most people

### ISSUE THREAD

**Issue by gwemon** [i-adopt/terminologies#8]
Feedback from @mabablue transferred from team discussion:
Please provide a list of terms and definitions of concepts you use to describe/name observable properties I know exactly what you mean here, because we often discussed this in the group, but we should ask somebody who was not involved in this process before, to find out if this is understandable.

**Comment by SirkoS** [comment]
(I hope I understand the goal of that question correctly)

Couldn't we reuse the example of the next question here? Basically move the example image (or something similar) to the top of the section and then in the description of the section mention something like 

> Following above example, this would result in the following entries 
>
> |  Name of   the entity  | Definition or link to definition if available online | Example relevant to case study |
> | --- | --- | --- |
> | ... | ...  | ...  |

---

Within the sheet there is the phrase "example relevant to case study".  By what criteria is a user to choose whether the terms are relevant? Is there any benefit over just asking for "example" and deciding on the relevancy afterwards, as the decision has to be made for the entities anyways.

---

Regarding the spreadsheet link - replace it with 
https://github.com/i-adopt/terminologies/raw/master/questionnaire_entities_definition_template.xlsx 

This link point directly to the file without requiring users to press download again.

**Comment by graybeal** [comment]
Without having time to review all the details, I like what @SirkoS seems to be doing here. 

About the original question, I agree testing would be good here, but let's just do the testing by having 2-4 people fill it out. That will test a lot of different things including this question.

**Comment by mabablue** [comment]
hi @gwemon can you explain to me why this question differs so much from the question in section 3 - please provide a list of nitrogen-related observable property names held in your terminology. I would simply use the same structure there as here, and here you are also asked to provide examples relevant to the nitrogen case study? For me this is double work.

**Comment by mariutzica** [comment]
@mabablue From the [original questionnaire](https://docs.google.com/document/d/1pWrKlNegViPb6xwVjQ9P2H5-IwqttZ7lFbLYbpN_aEo/edit), I think If I understand correctly that the difference between these questions is that one asks about the top-level concepts/classes (e.g. property, phenomenon,  matrix, quantity kind, matter, methodology, etc.) and how each is defined whereas the other question asks about specific instances (e.g., mass fraction of nitrogen in suspended sediment). Is that correct @gwemon ?

**Comment by mabablue** [comment]
yes and no @mariutzica, it asks for more. The name of the entity, the URI and a specific instance of that entity (so if the entity is matrix it wants a specific matrix entity, in this case Gwen provided suspended particulate material) . see here also my proposal issue 21 - I propose to use a similar excel sheet which would allow to add different examples but orders the entities differently: horizontally instead of vertically...
