### ISSUE TITLE
Issue related to request for diagram/other schematic representation of the relationships linking concepts

### ISSUE THREAD

**Issue by gwemon** [i-adopt/terminologies#9]
Feedback from @mabablue transferred from team discussion:
this is not applicable for controlled lists and this should be reflected in the question. Probably a question related to the specification language (XML, SKOS, RDF, OWL) would be helpful and along with the question about the relationships also a question about the existence of logic assertions could be added.

**Comment by SirkoS** [comment]
While there might be instances that do not have a model, I think even a controlled vocabulary has a basic model in mind. For example, if you provide a list of chemicals within the vocabulary you most likely imply that this is to be used as the substance that is actually measured. 
Following this, the question basically asks those controlled vocabularies to make their implicit assumptions explicit in a diagram.

**Comment by graybeal** [comment]
If we're just asking to provide any diagram that already exists (or can be easily captured), I don't see a problem.  

If we want the user to provide the context via a diagram they create, I think a higher-level diagram has to be provided to them,  to keep them from going off the rails. Something that illustrates all the different facets that might be involved, so at least they have a common terminology to work from. But arguably we don't know what those facets are yet, so I'd say it's premature to try to build these pictures.

With similar work for sensor ontologies 15 years ago, I found having a visual image very helpful, but in that case everything was an ontology and the main value added was to give a quick sense of the complexity and organization of the result. Asking people to draw that is not going to produce similar value.

**Comment by gwemon** [comment]
I should stress that this is not a mandatory question. If people do not have a diagram or a way of representing the relationships in their model or if it simply does not apply to them then that's fine. However if they do have relationships in their model then the best way to communicate these is graphically.

**Comment by gwemon** [comment]
@mabablue why do you need to know about the language at this stage? does it matter? THis is soemthing that can easily be worked out later on. Also what do you mean by "also a question about the existence of logic assertions"?
